version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
       - ./:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - postgres

volumes:
  pgdata:
    driver: local

networks:
  postgres:
    driver: bridge