version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:13.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
       - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - project-networks

volumes:
  pgdata:
    driver: local

networks:
  project-networks:
    driver: bridge
    name: ${POSTGRES_NET:-postgres}